/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'isSubscribed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'isSubscribed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };